class Config {
  final String id,
      title,
      logo,
      contact,
      email,
      copyright,
      address,
      favicon,
      currency,
      timezone,
      minOrder,
      tax,
      metaDescription,
      metaKeywords,
      analyticKey,
      pgCharge,
      about,
      aboutTitle,
      aboutMetaDescription,
      aboutMetaKeywords,
      privacy,
      privacyTitle,
      privacyMetaDescription,
      privacyMetaKeywords,
      terms,
      termsTitle,
      termsMetaDescription,
      termsMetaKeywords,
      refund,
      refundTitle,
      refundMetaDescription,
      refundMetaKeywords,
      registrationDescription,
      registrationTitle,
      razorpayKey,
      razorpaySecretKey,
      checkoutTitle,
      checkoutMetaDescription,
      checkoutMetaKeywords,
      syncStatus,
      sgst,
      cgst,
      packingCharge,
      deliveryCharge,
      deliveryTime;

  Config(
      {this.id,
      this.title,
      this.logo,
      this.contact,
      this.email,
      this.copyright,
      this.address,
      this.favicon,
      this.currency,
      this.timezone,
      this.minOrder,
      this.tax,
      this.metaDescription,
      this.metaKeywords,
      this.analyticKey,
      this.pgCharge,
      this.about,
      this.aboutTitle,
      this.aboutMetaDescription,
      this.aboutMetaKeywords,
      this.privacy,
      this.privacyTitle,
      this.privacyMetaDescription,
      this.privacyMetaKeywords,
      this.terms,
      this.termsTitle,
      this.termsMetaDescription,
      this.termsMetaKeywords,
      this.refund,
      this.refundTitle,
      this.refundMetaDescription,
      this.refundMetaKeywords,
      this.registrationDescription,
      this.registrationTitle,
      this.razorpayKey,
      this.razorpaySecretKey,
      this.checkoutTitle,
      this.checkoutMetaDescription,
      this.checkoutMetaKeywords,
      this.syncStatus,
      this.sgst,
      this.cgst,
      this.packingCharge,
      this.deliveryCharge,
      this.deliveryTime});

  Config.fromJson(Map<String, dynamic> json)
      : id = json['id'].toString(),
        title = json['title'].toString(),
        logo = json['logo'].toString(),
        contact = json['contact'].toString(),
        email = json['email'].toString(),
        copyright = json['copyright'].toString(),
        address = json['address'].toString(),
        favicon = json['favicon'].toString(),
        currency = json['currency'].toString(),
        timezone = json['timezone'].toString(),
        minOrder = json['min_order'].toString(),
        tax = json['tax'].toString(),
        metaDescription = json['meta_description'].toString(),
        metaKeywords = json['meta_keywords'].toString(),
        analyticKey = json['analytic_key'].toString(),
        pgCharge = json['pg_charge'].toString(),
        about = json['about'].toString(),
        aboutTitle = json['about_title'].toString(),
        aboutMetaDescription = json['about_meta_description'].toString(),
        aboutMetaKeywords = json['about_meta_keywords'].toString(),
        privacy = json['privacy'].toString(),
        privacyTitle = json['privacy_title'].toString(),
        privacyMetaDescription = json['privacy_meta_description'].toString(),
        privacyMetaKeywords = json['privacy_meta_keywords'].toString(),
        terms = json['terms'].toString(),
        termsTitle = json['terms_title'].toString(),
        termsMetaDescription = json['terms_meta_description'].toString(),
        termsMetaKeywords = json['terms_meta_keywords'].toString(),
        refund = json['refund'].toString(),
        refundTitle = json['refund_title'].toString(),
        refundMetaDescription = json['refund_meta_description'].toString(),
        refundMetaKeywords = json['refund_meta_keywords'].toString(),
        registrationDescription = json['registration_description'].toString(),
        registrationTitle = json['registration_title'].toString(),
        razorpayKey = json['razorpay_key'].toString(),
        razorpaySecretKey = json['razorpay_secret_key'].toString(),
        checkoutTitle = json['checkout_title'].toString(),
        checkoutMetaDescription = json['checkout_meta_description'].toString(),
        checkoutMetaKeywords = json['checkout_meta_keywords'].toString(),
        syncStatus = json['sync_status'].toString(),
        sgst = json['sgst'].toString(),
        cgst = json['cgst'].toString(),
        packingCharge = json['packing_charge'].toString(),
        deliveryCharge = json['delivery_charge'].toString(),
        deliveryTime = json['delivery_time'].toString();
}
